### ISSUE TITLE
Validate multipart/form-data formParameters

### ISSUE THREAD

**Issue by RETFU** [RETFU/RREST#11]
``` yaml
body:
    multipart/form-data:
        formParameters:
            XYZ:
                description: The file to be uploaded
                required: true
                type: file
```
